language: python
python:
  - "3.6"
env:
  - DISPLAY=:99.0
before_install:
  - sh -e /etc/init.d/xvfb start
install:
  - pip install pyqt5
  - pip install python-dateutil
  - pip install pytz
  - pip install lxml
  - pip install cryptography
  - git clone https://github.com/FreeOpcUa/python-opcua.git 
  - git clone https://github.com/FreeOpcUa/opcua-widgets.git 
# command to run tests
script: python3 tests.py
